### ISSUE TITLE
Export all palettes/colors

### ISSUE THREAD

**Issue by LeBenLeBen** [LeBenLeBen/palette#2]
To be able to save them and restore them later in the app.

**Comment by skynebula** [comment]
@LeBenLeBen Using the Sketch Palettes format would be ace!
https://github.com/andrewfiorillo/sketch-palettes

**Comment by LeBenLeBen** [comment]
@skynebula Yeah I think it's the most known/used out there and their format is pretty easy to generate, thanks!

This will be done in #4 tho.

**Comment by LeBenLeBen** [comment]
Added ability to export colors in multiple format in 4ed1159aa0ac04faf9c96047c8e0aa347e203018, let's close this and tackle import separately.
